config/routes.rb
Rails.application.routes.draw do
  # ------------------------------devise--------------------------------------------------
  devise_for :members, skip:[:registrations], controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords'
  }

  devise_scope :member do
    get 'members/sign_in', to: 'members/registrations#new'
    get 'members/sign_up' => 'members/registrations#new', as: :new_member_registration
    post 'members' => 'members/registrations#create', as: :member_registration
    get 'member/edit' => 'members/registrations#edit', as: :edit_member_registration
    #patch'members'=>'member'に変更 (membersコントローラ内のeditアクションと被るため)
    patch 'member' => 'members/registrations#update', as: nil
    put 'members' => 'members/registrations#update', as: :update_member_registration
    delete 'members' => 'members/registrations#destroy', as: :destroy_member_registration
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # --------------------------------devise------------------------------------------------

  # --------------------------------members----------------------------------------------

  scope module: :member do

    root to: 'home#top'
    get 'about', to: 'home#about'

    resource :members, only: [:show, :edit, :update] do

      resources :cart_items, only: [:index, :update, :destroy, :create]
      delete 'cart_items', to: 'cart_items#destroy_all'

      resources :delivery_addresses, only: [:index, :create, :edit, :update, :destroy]

    end

    get 'orders/confirm', to: 'orders#confirm'
    get 'orders/complete', to: 'orders#complete'

    resources :orders, only: [:new, :create, :show, :index]

    get 'members/resignation', to: 'members#resignation'
    patch 'members/quit', to: 'members#quit'

    resources :items, only: [:index, :show]

  end

  # --------------------------------members----------------------------------------------

  # --------------------------------admin----------------------------------------------

  get 'admin/top', to: 'admin/home#top'

  namespace :admin do

    resources :members, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]

  end
  # -----------------------------------admin--------------------------------------------

end

# 最新ver.--------

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :order_details, dependent: :destroy

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1, "代引き": 2 }

  validates :name, :address, :postcode, presence: true
  validates :postcode, length: { is: 7 } , numericality: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    # もし注文ステータスが1なら
    if order.status == 1
      order.order_details.each do |order_detail|
        # 製作ステータスを1に変更する。
        order_detail.update(status: 1)
      end
    end
    redirect_to admin_order_path(order)
  end

  private
  def order_params
    params.require(:order).permit(
      :created_at,
      :address,
      :name,
      :status,
      :payment_method,
      :postcode,
      :postage,
      :member_id,
      :total_price,
      order_details_attributes: [:order_id, :item_id, :quantity, :purchase, :status]
    )
  end
end

app/controllers/member/orders_controller.rb
class Member::OrdersController < ApplicationController
  before_action :authenticate_member!
  before_action :set_member

  def new
    @order = Order.new
  end

  def confirm
    @order = Order.new
    @cart_items = current_member.cart_items
    @order.payment_method = params[:order][:payment_method]
    @add = params[:order][:add].to_i

    case @add
      when 0 # あなたの住所
        @order.postcode = @member.postcode
        @order.address = @member.address
        @order.name = @member.last_name + @member.first_name
      when 1 # 登録住所
        @sta = params[:order][:address].to_i
        @address = DeliveryAddress.find(@sta)
        @order.postcode = @address.postcode
        @order.address = @address.address
        @order.name = @address.name
      when 2 # 新しいお届け先
        @order.postcode = params[:order][:new_add][:postcode]
        @order.address = params[:order][:new_add][:address]
        @order.name = params[:order][:new_add][:name]
    end
  end

  def create
    if current_member.cart_items.exists?
      @order = Order.new(order_params)
      @order.member_id = current_member.id
      @order.save
      

      # addressで住所モデル検索、該当データなければ新規作成
      if DeliveryAddress.find_by(address: @order.address).nil?
        @address = DeliveryAddress.new
        @address.postcode = @order.postcode
        @address.address = @order.address
        @address.name = @order.name
        @address.member_id = current_member.id
        @address.save
        
      end

      # cart_itemsの内容をorder_detailsに新規登録
      current_member.cart_items.each do |cart_item|
        order_detail = @order.order_details.build
        order_detail.order_id = @order.id
        order_detail.item_id = cart_item.item_id
        order_detail.quantity = cart_item.quantity
        order_detail.purchase = cart_item.total_price
        order_detail.save
        cart_item.destroy #order_detailに情報を移したらcart_itemは消去
      end
      flash[:success] = "ご注文が確定しました。"
      render :complete
    else
      flash[:alert] = "カートに商品を入れてください！"
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @orders = @member.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  def complete
  end

  private

  def set_member
    @member = current_member
  end

  def order_params
    params.require(:order).permit(
      :created_at,
      :address,
      :name,
      :status,
      :payment_method,
      :postcode,
      :postage,
      :member_id,
      :total_price,
      order_details_attributes: [:order_id, :item_id, :quantity, :purchase, :status]
      )
  end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/member/orders_helper.rb
module Member::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="admin_main_visual">注文履歴一覧</h1>
    <div class="col-xs-2"></div>
      <div class="col-xs-6">

        <table class="table table-hover">
          <thead>
            <tr>
              <td>購入日時</td>
              <td>購入者</td>
              <td>注文個数</td>
              <td>注文ステータス</td>
            </tr>
          </thead>

          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td><%= link_to order.created_at.strftime("%Y-%m-%d"), admin_order_path(order) %></td>
                <td><%= order.name %></td>
                <td><%= order.order_details.sum(:quantity) %></td>
                <% if order.status == 0 %>
                  <td><%= "入金待ち" %></td>
                <% elsif order.status == 1 %>
                  <td><%= "入金確認" %></td>
                <% elsif order.status == 2 %>
                  <td><%= "製作中" %></td>
                <% elsif order.status == 3 %>
                  <td><%= "発送準備中" %></td>
                <% else order.status == 4 %>
                  <td><%= "発送済み" %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h1 class="admin_main_visual">注文履歴詳細</h3>
  <div class="row">
    <div class="col-xs-8">
      <table class="table">
        <tr>
          <th>購入者</th><td><%= @order.name %></td>
        </tr>
        <tr>
          <th>配送先</th><td><%= @order.postcode %><%= @order.address %></td>
        </tr>
        <tr>
          <th>支払方法</th><td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path, local: true do |f| %>
            <%= f.select :status, [["入金待ち", 0], ["入金確認", 1], ["製作中", 2], ["発送準備中", 3], ["発送済み", 4]] %>
            <%= f.submit '更新', class:"btn btn-primary" %>
          </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-8">
        <table class="table">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= tax_price(order_detail.item.price) %></td>
              <td><%= order_detail.quantity %></td>
              <td><%= tax_price(order_detail.item.price) * order_detail.quantity %></td>

              <% if order_detail.status == 0 %>
                <td>着手不可</td>
              <% elsif order_detail.status == 1 %>
                <td>製作待ち</td>
              <% elsif order_detail.status == 2 %>
                <td>製作中</td>
              <% elsif order_detail.status == 3 %>
                <td>製作完了</td>
              <% end %>

              <td><%= form_with model: order_detail, url: admin_order_detail_path(order_detail), local: true do |f| %>
                <%= f.select :status, [["着手不可", 0], ["製作待ち", 1], ["製作中", 2], ["製作完了", 3]] %>
                <%= f.submit '更新', class:"btn btn-primary" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    <div class="col-xs-4">
        <table class="table table-striped table-bordered table-condensed">
          <tr><th><p>商品合計</p></th><td><%= @order.total_price - @order.postage %>円</td></tr>
          <tr><th><p>送料</p></th><td><%= @order.postage %>円</td></tr>
          <tr><th>請求金額合計</th><td><%= @order.total_price %>円</td></tr>
        </table>

      </div>

  </div>
</div>