config/routes.rb
Rails.application.routes.draw do
  # ------------------------------devise--------------------------------------------------
  devise_for :members, skip:[:registrations], controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords'
  }

  devise_scope :member do
    get 'members/sign_in', to: 'members/registrations#new'
    get 'members/sign_up' => 'members/registrations#new', as: :new_member_registration
    post 'members' => 'members/registrations#create', as: :member_registration
    get 'member/edit' => 'members/registrations#edit', as: :edit_member_registration
    #patch'members'=>'member'に変更 (membersコントローラ内のeditアクションと被るため)
    patch 'member' => 'members/registrations#update', as: nil
    put 'members' => 'members/registrations#update', as: :update_member_registration
    delete 'members' => 'members/registrations#destroy', as: :destroy_member_registration
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # --------------------------------devise------------------------------------------------

  # --------------------------------members----------------------------------------------

  scope module: :member do

    root to: 'home#top'
    get 'about', to: 'home#about'

    resource :members, only: [:show, :edit, :update] do

      resources :cart_items, only: [:index, :update, :destroy, :create]
      delete 'cart_items', to: 'cart_items#destroy_all'

      resources :delivery_addresses, only: [:index, :create, :edit, :update, :destroy]

    end

    get 'orders/confirm', to: 'orders#confirm'
    get 'orders/complete', to: 'orders#complete'

    resources :orders, only: [:new, :create, :show, :index]

    get 'members/resignation', to: 'members#resignation'
    patch 'members/quit', to: 'members#quit'

    resources :items, only: [:index, :show]

  end

  # --------------------------------members----------------------------------------------

  # --------------------------------admin----------------------------------------------

  get 'admin/top', to: 'admin/home#top'

  namespace :admin do

    resources :members, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]

  end
  # -----------------------------------admin--------------------------------------------

end

# 最新ver.--------

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :order_details, dependent: :destroy

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1, "代引き": 2 }

  validates :name, :address, :postcode, presence: true
  validates :postcode, length: { is: 7 } , numericality: true

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    member = Member.find(params[:id])
    member.update(member_params)
    redirect_to admin_member_path(member)
  end

  private
  def member_params
    params.require(:member).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :postcode, :address, :phone_number, :emai, :is_delete)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    # もし注文ステータスが1なら
    if order.status == 1
      order.order_details.each do |order_detail|
        # 製作ステータスを1に変更する。
        order_detail.update(status: 1)
      end
    end
    redirect_to admin_order_path(order)
  end

  private
  def order_params
    params.require(:order).permit(
      :created_at,
      :address,
      :name,
      :status,
      :payment_method,
      :postcode,
      :postage,
      :member_id,
      :total_price,
      order_details_attributes: [:order_id, :item_id, :quantity, :purchase, :status]
    )
  end
end

app/controllers/member/cart_items_controller.rb
class Member::CartItemsController < ApplicationController

  before_action :authenticate_member!
  before_action :set_cart_item, only: [:edit, :update, :destroy]
  before_action :set_member

    # カート内商品一覧
  def index
    @member = current_member
    @cart_items = @member.cart_items.all
  end

  def create
    # ログイン会員の空のカート作成
    @cart_item = current_member.cart_items.build(cart_item_params)
    # 現在カートに入っている商品
    @current_item = CartItem.find_by(item_id: @cart_item.item_id)
    # カートに同じ商品がなければ新規追加、あれば既存のデータと合算
    if @current_item.nil?
      if @cart_item.save
        flash[:success] = 'カートに商品が追加されました！'
        redirect_to members_cart_items_path
      else
        # ログイン会員のカート内の全商品
        @cart_items = @member.cart_items.all
        render 'index'
        flash[:alert] = 'カートに商品を追加できませんでした。'
      end
      # カートが空じゃないとき
    else
      # paramsで取ってくると文字列になるので".to_i"が必要!
      @current_item.quantity += params[:cart_item][:quantity].to_i
      # カート内商品を更新
      @current_item.update(quantity: @current_item.quantity)
      # カート内商品一覧画面へ遷移
      redirect_to members_cart_items_path
    end
  end

  def update
    @current_item = CartItem.find_by(item_id: @cart_item.item_id)
    @current_item.quantity = params[:cart_item][:quantity]
    @cart_item.update(quantity: @current_item.quantity)
    flash[:update] = '数量を変更しました。'
    redirect_to members_cart_items_path
  end

  def destroy
    @cart_item.destroy
    flash[:alert] = "#{@cart_item.item.name}を削除しました"
    redirect_to members_cart_items_path
  end

  def destroy_all
    @cart_items = current_member.cart_items
    @cart_items.destroy_all
    flash[:alert] = "カートの商品を全て削除しました"
    redirect_to members_cart_items_path
  end

  private

  # ログインしている会員
  def set_member
    @member = current_member
  end

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :member_id, :quantity, :image)
  end
end

app/controllers/member/delivery_address_controller.rb
class Member::DeliveryAddressController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/member/delivery_addresses_controller.rb
class Member::DeliveryAddressesController < ApplicationController
  def index
    @member = current_member
    @delivery_addresses = @member.delivery_addresses
    @delivery_address = DeliveryAddress.new
  end

  def create
    @delivery_address = DeliveryAddress.new(delivery_address_params)
    @delivery_address.member_id = current_member.id
    if @delivery_address.save
      flash[:success] = "配送先を登録しました。"
      redirect_to members_delivery_addresses_path
    else
      flash[:alert] = "正しい値を入力してください。"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @delivery_address = DeliveryAddress.find(params[:id])
  end

  def update
    @delivery_address = DeliveryAddress.find(params[:id])
    if @delivery_address.update(delivery_address_params)
      flash[:success] = "配送先を更新しました。"
      redirect_to members_delivery_addresses_path, notice: "You have updated book successfully."
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "正しい値を入力してください。"
    end
  end

  def destroy
    @delivery_address = DeliveryAddress.find(params[:id])
    @delivery_address.destroy
    flash[:alert] = "配送先を1件削除しました。"
    redirect_to members_delivery_addresses_path
  end

  private
  def delivery_address_params
    params.require(:delivery_address).permit(:member_id, :postcode, :address, :name)
  end
end

app/controllers/member/home_controller.rb
class Member::HomeController < ApplicationController
  def top
    # genreのis_activeが有効の商品から4件表示
    @items = Item.joins(:genre).where(genres: {is_active: "true"}).limit(4)
    @genres = Genre.where(is_active: true)

  end

  def about
  end
end

app/controllers/member/items_controller.rb
class Member::ItemsController < ApplicationController

  def index
    # @item_all = ページネーション使用時の全商品count用
    @genres = Genre.where(is_active: true)
    if params[:genre_id].present?
      @items = Item.where(genre_id: params[:genre_id]).page(params[:page]).per(8)
      @genre = Genre.find(params[:genre_id])
      @item_all = Item.where(genre_id: params[:genre_id])
    else
      # genres有効の商品のみ表示
      @items = Item.joins(:genre).where(genres: {is_active: "true"}).page(params[:page]).per(8)
      @item_all = Item.joins(:genre).where(genres: {is_active: "true"})
    end
  end

  def show
    @genres = Genre.all
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
end

app/controllers/member/members_controller.rb
class Member::MembersController < ApplicationController
  before_action :authenticate_member!
  def show
    @member = Member.find(current_member.id)
  end

  def edit
    @member = Member.find(current_member.id)
  end

  def update
    @member = Member.find(current_member.id)
    if @member.update(member_params)
      redirect_to members_path
      flash[:notice_update] = "会員情報が更新されました。"
    else
      flash[:alert_update] = "正しい値を入力してください。"
      redirect_back(fallback_location: root_path)
    end
  end

  def resignation
    @member = Member.find(current_member.id)
  end

  def quit
    @member = Member.find(current_member.id)
    #is_deletedカラムにフラグを立てる(defaultはfalse)
    @member.update(is_delete: true)
    #ログアウトさせる
    reset_session
    flash[:resignation] = "◆退会処理が完了しました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private
  def member_params
    params.require(:member).permit(
      :first_name, 
      :last_name, 
      :kana_first_name, 
      :kana_last_name, 
      :postcode, 
      :address, 
      :phone_number, 
      :email, 
      :is_delete,
      :prefecture_name,
      :prefecture_code
    )
  end
end

app/controllers/member/orders_controller.rb
class Member::OrdersController < ApplicationController
  before_action :authenticate_member!
  before_action :set_member

  def new
    @order = Order.new
  end

  def confirm
    @order = Order.new
    @cart_items = current_member.cart_items
    @order.payment_method = params[:order][:payment_method]
    @add = params[:order][:add].to_i

    case @add
      when 0 # あなたの住所
        @order.postcode = @member.postcode
        @order.address = @member.address
        @order.name = @member.last_name + @member.first_name
      when 1 # 登録住所
        @sta = params[:order][:address].to_i
        @address = DeliveryAddress.find(@sta)
        @order.postcode = @address.postcode
        @order.address = @address.address
        @order.name = @address.name
      when 2 # 新しいお届け先
        @order.postcode = params[:order][:new_add][:postcode]
        @order.address = params[:order][:new_add][:address]
        @order.name = params[:order][:new_add][:name]
    end
  end

  def create
    if current_member.cart_items.exists?
      @order = Order.new(order_params)
      @order.member_id = current_member.id
      @order.save
      

      # addressで住所モデル検索、該当データなければ新規作成
      if DeliveryAddress.find_by(address: @order.address).nil?
        @address = DeliveryAddress.new
        @address.postcode = @order.postcode
        @address.address = @order.address
        @address.name = @order.name
        @address.member_id = current_member.id
        @address.save
        
      end

      # cart_itemsの内容をorder_detailsに新規登録
      current_member.cart_items.each do |cart_item|
        order_detail = @order.order_details.build
        order_detail.order_id = @order.id
        order_detail.item_id = cart_item.item_id
        order_detail.quantity = cart_item.quantity
        order_detail.purchase = cart_item.total_price
        order_detail.save
        cart_item.destroy #order_detailに情報を移したらcart_itemは消去
      end
      flash[:success] = "ご注文が確定しました。"
      render :complete
    else
      flash[:alert] = "カートに商品を入れてください！"
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @orders = @member.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  def complete
  end

  private

  def set_member
    @member = current_member
  end

  def order_params
    params.require(:order).permit(
      :created_at,
      :address,
      :name,
      :status,
      :payment_method,
      :postcode,
      :postage,
      :member_id,
      :total_price,
      order_details_attributes: [:order_id, :item_id, :quantity, :purchase, :status]
      )
  end
  
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  
  before_action :reject_member, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  protected

  def reject_member
    @member = Member.find_by(email: params[:member][:email].downcase)
    if @member
      if (@member.valid_password?(params[:member][:password]) && (@member.active_for_authentication? == false))
        flash[:error] = "このアカウントは退会済みです。"
        redirect_to new_member_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/member/cart_items_helper.rb
module Member::CartItemsHelper
end

app/views/member/orders/complete.html.erb
<% if flash[:success] %>
  <p class="alert alert-info">
    <%= flash[:success] %>
  </p>
<% end %>

<h1 class="text-center">
  <%= current_member.last_name %>
  <%= current_member.first_name %>
  様、ご購入ありがとうございます！
</h1>

<%= video_tag("/assets/videos/thankyou_page.mp4", :autoplay => true, :loop => true, muted: :true, width: "100%", height: "500px") %>

app/views/member/orders/confirm.html.erb
<% if flash[:alert] %>
  <p class="alert alert-danger">
    <%= flash[:alert] %>
  </p>
<% end %>

<div class="container">
  <h1>注文情報確認</h1>
  <div class="row">
    <div class="col-xs-7">
      <%= form_with(model: @order, url: orders_path, local: true) do |f| %>
        <table class="table">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
          <% @sum = 0 %>
          <% @cart_items.each do |cart_item| %>
            <tr>
              <td><%= cart_item.item.name %></td>
              <td><%= tax_price(cart_item.item.price).to_s(:delimited) %></td>
              <td><%= cart_item.quantity %></td>
              <td><%= (tax_price(cart_item.item.price) * cart_item.quantity).to_s(:delimited) %></td>
            </tr>
            <% @sum += tax_price(cart_item.item.price) * cart_item.quantity %>
          <% end %>
        </table>
    </div>

    <div class="col-xs-3">
      <table class="table table-striped">
        <tr>
          <th>送料</th>
          <td><%= @order.postage %></td>
        </tr>
        <tr>
          <th>商品合計</th>
          <td><%= @sum.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>請求金額</th>
          <td><%= (@sum + @order.postage).to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>

    <div class="row">
      <div class="col-xs-6">
        <table class="table">
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method %></td>
          </tr>
          <tr>
            <th>お届け先</th>
            <td>
              〒<%= @order.postcode %>
              <%= @order.address %>
            </td>
          </tr>
          <tr>
            <th>宛名</th>
            <td><%= @order.name %></td>
          </tr>
        </table>
      </div>
    </div>
    

    <%= f.hidden_field :member_id, :value => current_member.id %>
    <%= f.hidden_field :postcode, :value => "#{@order.postcode}" %>
    <%= f.hidden_field :address, :value => "#{@order.address}" %>
    <%= f.hidden_field :name, :value => "#{@order.name}" %>
    <%= f.hidden_field :total_price, :value => "#{@sum + @order.postage}" %>
    <%= f.hidden_field :payment_method, :value => "#{@order.payment_method}" %>

      <div class="text-center">
        <%= f.submit "購入を確定する", class: "btn btn-primary" %>
      </div>
    
    <% end %>
</div>

app/views/member/orders/index.html.erb
<div class="container">
  <div class="row">

    <label>注文履歴一覧</label>

    <table class="table">
        <thead>
          <tr>
            <th>注文日</th>
            <th>配送先</th>
            <th>注文商品</th>
            <th>支払金額</th>
            <th>ステータス</th>
            <th>注文詳細</th>
          </tr>
        </thead>
      <% @orders.each do |order| %>
          <tr>
            <td><%= order.created_at.strftime("%Y-%m-%d") %></td>
            <td>
              <%= order.postcode %><br>
              <%= order.address %><br>
              <%= order.name %><br>
            </td>
            <td>
            <% order.order_details.each do |order_detail| %>
              <%= order_detail.item.name %><br>
            <% end %>
          </td>

          <td><%= order.total_price %></td>
        <% if order.status == 0 %>
          <td><%= "入金待ち" %></td>
        <% elsif order.status == 1 %>
          <td><%= "入金確認" %></td>
        <% elsif order.status == 2 %>
          <td><%= "製作中" %></td>
        <% elsif order.status == 3 %>
          <td><%= "発送準備中" %></td>
        <% else order.status == 4 %>
          <td><%= "発送済み" %></td>
        <% end %>
        <td><%= link_to "表示する", order_path(order) %>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/member/orders/new.html.erb
<div class="container">
 
  <h1>注文情報入力</h1>

  <h2><strong>支払方法</strong></h2>

  <%= form_with(model: @order, url: orders_confirm_path, method: :get, local: true) do |f| %>
      <p><%= f.radio_button :payment_method, :"クレジットカード", checked: true %>クレジットカード</p>
      <p><%= f.radio_button :payment_method, :"銀行振込" %>銀行振込</p>
      <p><%= f.radio_button :payment_method, :"代引き" %>代引き</p>

      <h2><strong>お届け先</strong></h2>

      <p><%= f.radio_button :add, 0, checked: true %>あなたの住所</p>
        〒<%= @member.postcode %>
        <%= @member.address %>
        <%= @member.last_name %>
        <%= @member.first_name %>

      <p><%= f.radio_button :add, 1 %>登録住所から選択</p>
        <%= f.collection_select :address, @member.delivery_addresses, :id, :order_address %>

      <p><%= f.radio_button :add, 2 %>新しいお届け先</p>
        <%= f.fields_for :new_add do |f| %>
          <p>郵便番号(ハイフンなし) <%= f.text_field :postcode %></p>
          <p>住所 <%= f.text_field :address %></p>
          <p>宛名 <%= f.text_field :name %></p>
        <% end %>


      <p class="text-center">
        <%= f.submit "確認画面へ進む", class: "btn btn-primary" %>  
      </p>
  <% end %>
 
</div>

app/views/member/orders/show.html.erb
<div class="container">
  <h3>注文履歴詳細</h3>
  <div class="row">

    <div class="col-xs-7">
      <h4><strong>注文情報</strong></h4>
      <table class="table">
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <%= @order.postcode %>
            <%= @order.address %>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>ステータス</th>
          <% if @order.status == 0 %>
            <td><%= "入金待ち" %></td>
          <% elsif @order.status == 1 %>
            <td><%= "入金確認" %></td>
          <% elsif @order.status == 2 %>
            <td><%= "製作中" %></td>
          <% elsif @order.status == 3 %>
            <td><%= "発送準備中" %></td>
          <% else @order.status == 4 %>
            <td><%= "発送済み" %></td>
          <% end %>
        </tr>
      </table>
    </div>

    <div class="col-xs-3">
      <h4><strong>請求情報</strong></h4>
      <table class="table table-striped">
        <tr>
          <th>商品合計</th>
          <td><%= (@order.total_price - @order.postage).to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>配送料</th>
          <td><%= @order.postage.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>ご請求額</th>
          <td><%= @order.total_price.to_s(:delimited) %></td>
        </tr>
      </table>
    </div>

    <div class="col-xs-8">
      <h4><strong>注文内容</strong></h4>
      <table class="table">
        <thead>
          <tr>
          <th></th>
            <th>商品</th>
            <th>単価（税込）</th>
            <th>個数</th>
            <th>小計</th>
          </tr>
        </thead>

        <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= attachment_image_tag order_detail.item, :image, format: 'jpeg', fallback: "no-image.jpg", size: "160x120" %></td>
            <td><%= order_detail.item.name %></td>
            <td><%= tax_price(order_detail.item.price).to_s(:delimited) %></td>
            <td><%= order_detail.quantity %></td>
            <td><%= (tax_price(order_detail.item.price) * order_detail.quantity).to_s(:delimited) %></td>
          </tr>
        <% end %>

      </table>
    </div>

  </div>
</div>