config/routes.rb
Rails.application.routes.draw do
  # ------------------------------devise--------------------------------------------------
  devise_for :members, skip:[:registrations], controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords'
  }

  devise_scope :member do
    get 'members/sign_in', to: 'members/registrations#new'
    get 'members/sign_up' => 'members/registrations#new', as: :new_member_registration
    post 'members' => 'members/registrations#create', as: :member_registration
    get 'member/edit' => 'members/registrations#edit', as: :edit_member_registration
    #patch'members'=>'member'に変更 (membersコントローラ内のeditアクションと被るため)
    patch 'member' => 'members/registrations#update', as: nil
    put 'members' => 'members/registrations#update', as: :update_member_registration
    delete 'members' => 'members/registrations#destroy', as: :destroy_member_registration
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # --------------------------------devise------------------------------------------------

  # --------------------------------members----------------------------------------------

  scope module: :member do

    root to: 'home#top'
    get 'about', to: 'home#about'

    resource :members, only: [:show, :edit, :update] do

      resources :cart_items, only: [:index, :update, :destroy, :create]
      delete 'cart_items', to: 'cart_items#destroy_all'

      resources :delivery_addresses, only: [:index, :create, :edit, :update, :destroy]

    end

    get 'orders/confirm', to: 'orders#confirm'
    get 'orders/complete', to: 'orders#complete'

    resources :orders, only: [:new, :create, :show, :index]

    get 'members/resignation', to: 'members#resignation'
    patch 'members/quit', to: 'members#quit'

    resources :items, only: [:index, :show]

  end

  # --------------------------------members----------------------------------------------

  # --------------------------------admin----------------------------------------------

  get 'admin/top', to: 'admin/home#top'

  namespace :admin do

    resources :members, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]

  end
  # -----------------------------------admin--------------------------------------------

end

# 最新ver.--------

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :member

  validates :member_id, :item_id, :quantity, presence: true

  def total_price
		item.price*quantity
  end
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
	belongs_to :member

	validates :postcode, length: { is: 7 } , numericality: true
	validates :address, presence: true
	validates :name, presence: true

	def order_address
		"〒" +self.postcode + "　" + self.address + "　" + self.name
	end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :is_active, inclusion: {in: [true, false]}
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  attachment :image
  validates :genre_id, :name, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :explanation, presence: true
  validates :is_active, inclusion: {in: [true, false]}
end

app/models/member.rb
class Member < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :delivery_addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :kana_last_name, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :phone_number, format: {with: /\A\d{10}\z|\A\d{11}\z/}
  validates :address, presence: true
  validates :postcode, length: { is: 7 } , numericality: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, presence: true

  def full_name
		last_name + first_name
  end

  #------------------退会関連-----------------------------------

  def active_for_authentication?
    super && (self.is_delete == false)
  end

  def inactive_message
    self.is_delete? ? super : :special_condition_is_not_valid
  end

   #------------------------------------------------------------

   #------------------住所自動入力関連----------------------------
   include JpPrefecture
   jp_prefecture :prefecture_code

   def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
   end

   def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
   end

  #------------------住所自動入力関連----------------------------

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :order_details, dependent: :destroy

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1, "代引き": 2 }

  validates :name, :address, :postcode, presence: true
  validates :postcode, length: { is: 7 } , numericality: true

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :order_id, :item_id, :quantity, :purchase, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :info, :warning, :danger

  before_action :set_search
  def set_search
    @search_i = Item.ransack(params[:q])
    @search_items = @search_i.result

    @search_m = Member.ransack(params[:q])
    @search_members = @search_m.result

    @search_g = Genre.ransack(params[:q])
    @search_genres = @search_g.result
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
    	:email,
    	:last_name,
      :first_name,
      :kana_last_name,
      :kana_first_name,
      :phone_number,
      :address,
      :postcode,
      :prefecture_name,
      :prefecture_code
    ])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_top_path
    when Member
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    return new_admin_session_path if resource_or_scope == :admin
    root_path
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def tax_price(price)
    (price * 1.1).floor
  end
end

app/helpers/member/home_helper.rb
module Member::HomeHelper
end

app/helpers/member/items_helper.rb
module Member::ItemsHelper
end

app/helpers/member/members_helper.rb
module Member::MembersHelper
end

app/helpers/member/orders_helper.rb
module Member::OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-info" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name),class: "btn btn-info" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CakeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar">
        <div class="container">
          <span class="navbar-toggler-icon">
            <div class="col-xs-3">
              <% if member_signed_in? %>
                <%= link_to image_tag("h_logo.jpg"), root_path %>
              <% elsif admin_signed_in? %>
                <%= link_to image_tag("h_logo.jpg"), admin_top_path %>
              <% else %>
                <%= link_to image_tag("h_logo.jpg"), root_path %>
              <% end%>
            </div>
          </span>
            <div class="col-xs-9">
              <div class="menu">
                <ul class="nav navbar-nav navbar-right">
                <% if member_signed_in? %>
                    <li  class="head-name">ようこそ、<%= current_member.last_name %> <%= current_member.first_name %>さん！</li>
                    <li><%= link_to members_path(current_member), class:"btn btn-default" do %>
                      <i class="nav-link active"></i>マイページ</li><% end %>
                    <li><%= link_to items_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>商品一覧</li><% end %>
                    <li><%= link_to members_cart_items_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>カート</li><% end %>
                    <li><%= link_to destroy_member_session_path,  method: :delete, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>ログアウト</li><% end %>
                <% elsif admin_signed_in? %>
                  <%# 商品検索 %>
                  <% if current_page?(admin_items_path) %>
                    <%= search_form_for @search_i, url: admin_items_path do |f| %>
                      <%= f.text_field :name_cont ,placeholder: "商品名を入力" %>
                      <%= f.submit ("検索") , class: "search-btn"%>
                    <% end %>
                  <%# 会員検索 %>
                  <% elsif current_page?(admin_members_path) %>
                    <%= search_form_for @search_m, url: admin_members_path do |f| %>
                      <%= f.text_field :first_name_or_last_name_cont ,placeholder: "会員名を入力" %>
                      <%= f.submit ("検索") , class: "search-btn"%>
                    <% end %>
                  <%# ジャンル検索 %>
                  <% elsif current_page?(admin_genres_path) %>
                    <%= search_form_for @search_g, url: admin_genres_path do |f| %>
                      <%= f.text_field :name_cont ,placeholder: "ジャンル名を入力" %>
                      <%= f.submit ("検索") , class: "search-btn"%>
                    <% end %>
                  <% else %>
                  <%# 上記path以外では検索フォームを表示しない %>
                  <% end %>
                  <%= link_to admin_items_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>商品一覧</li><% end %>
                    <%= link_to admin_members_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>会員一覧</li><% end %>
                    <%= link_to admin_orders_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>注文履歴一覧</li><% end %>
                    <%= link_to admin_genres_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>ジャンル一覧</li><% end %>
                    <%= link_to destroy_admin_session_path, method: :delete, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>ログアウト</li><% end %>
                  <% elsif %>
                    <li><%= link_to about_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>About</li><% end %>
                    <li><%= link_to items_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>商品一覧</li><% end %>
                    <li><%= link_to new_member_registration_path, data: {"turbolinks"=>false}, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>新規登録</li><% end %>
                    <li><%= link_to new_member_session_path, class:"btn btn-default" do %>
                      <i class="nav-link active"></i>ログイン</li><% end %>
                  <% end %>
              </ul>
                </ul>
              </div>
            </div>
        </div>
      </nav>
    </header>

    <div class="main_body">
      <%= yield %>
    </div>
    
       <!--footer-->
    <footer>
      <p>2020©karaage.from.infratop</p>

      <i class="fab fa-twitter-square fa-2x"></i>
      <i class="fab fa-instagram-square fa-2x"></i>
      <i class="fab fa-line fa-2x"></i>
    </footer>
      <!--footer-->

  </body>
</html>